apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cards-service.fullname" . }}-config
  labels:
    {{- include "cards-service.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.spring.profiles | quote }}
  SERVER_PORT: {{ .Values.service.port | quote }}
  MANAGEMENT_SERVER_PORT: {{ .Values.service.managementPort | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.database.url | quote }}
