apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cards-service.fullname" . }}-secret
  labels:
    {{- include "cards-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.database.username | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
  JWT_SECRET: {{ .Values.jwt.secret | quote }}
