apiVersion: apps/v1
kind: Deployment
metadata:
  name: cards-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cards-service
  template:
    metadata:
      labels:
        app: cards-service
    spec:
      containers:
        - name: cards-service
          image: cards-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 2001
          env:
            - name: SERVER_PORT
              value: "2001"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/elevens-bank"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"
---
apiVersion: v1
kind: Service
metadata:
  name: cards-service
spec:
  selector:
    app: cards-service
  ports:
    - protocol: TCP
      port: 2001
      targetPort: 2001
