version: "3.8"

services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.3
    volumes:
      - ./pipeline/:/usr/share/logstash/pipeline/
      - ./drivers/:/usr/share/logstash/drivers/
      - /home/shrikar/Bank/elevens-bank:/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - LS_JAVA_OPTS=-Xms192m -Xmx192m
      - XPACK_MONITORING_ENABLED=false
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: 512m
